# Generated by Django 3.0 on 2019-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_model',
            name='date',
            field=models.CharField(help_text='MMDDYYYY', max_length=8),
        ),
    ]
