# Generated by Django 3.0 on 2019-12-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20191208_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_model',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown Age', 'Unknown Age')], max_length=30),
        ),
    ]
