# Generated by Django 3.0 on 2019-12-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20191208_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_model',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=30),
        ),
    ]
