# Generated by Django 2.2.7 on 2019-12-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_auto_20191208_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_model',
            name='date',
            field=models.CharField(help_text='(Format: MMDDYYYY)', max_length=8),
        ),
        migrations.AlterField(
            model_name='st_model',
            name='other_activities',
            field=models.CharField(blank=True, help_text='(200 characters or less.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='st_model',
            name='specific_location',
            field=models.CharField(blank=True, help_text='(200 characters or less.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='st_model',
            name='unique_squirrel_id',
            field=models.CharField(help_text='(ID Format: Hectare-Shift-MMDD-Hectare Squirrel Number)', max_length=30),
        ),
    ]
